---
- name: Add hnakamur/apache-traffic-server repository on copr
  get_url: url={{ trafficserver_yum_repo_file_url }} dest=/etc/yum.repos.d/{{ trafficserver_yum_repo_file_name }}
  tags: ["trafficserver"]

- name: Install Apache Traffic Server
  yum: name=trafficserver state=latest
  tags: ["trafficserver"]

- name: Write trafficserver config files
  template: src={{ item }} dest=/etc/trafficserver/{{ item | regex_replace('\.j2$', '') }}
  notify: restart trafficserver
  with_items:
    - cache.config.j2
    - plugin.config.j2
    - records.config.j2
    - remap.config.j2
    - logs_xml.config.j2
    - storage.config.j2
  tags: ["trafficserver"]

#- name: Write /etc/trafficserver/records.config
#  template: src=records.config.j2 dest=/etc/trafficserver/records.config
#  notify: restart trafficserver
#  tags: ["trafficserver"]
#
#- name: Write /etc/trafficserver/remap.config
#  template: src=remap.config.j2 dest=/etc/trafficserver/remap.config
#  notify: restart trafficserver
#  tags: ["trafficserver"]

- name: Start and enable trafficserver service
  service: name=trafficserver state=started enabled=True
  tags: ["trafficserver"]
