---
- name: Check wordpress test data is already installed
  stat: path=/root/wordpress-test-data-with-lots-of-photos-ja.xml
  register: wordpres_test_data_xml_st
  tags: ["wordpress_test_data"]

- name: Copy xml for wordpress test data
  copy: src=wordpress-test-data-with-lots-of-photos-ja.xml dest=/root/wordpress-test-data-with-lots-of-photos-ja.xml
  when: not wordpres_test_data_xml_st.stat.exists
  tags: ["wordpress_test_data"]

- name: Install wordpress-importer plugin
  command: php70 /usr/local/bin/wp plugin install wordpress-importer --path={{ wordpress_install_dir }} --activate
  when: not wordpres_test_data_xml_st.stat.exists
  tags: ["wordpress_test_data"]

- name: Install wordpress test data
  command: php70 /usr/local/bin/wp import --path={{ wordpress_install_dir }} --authors=create /root/wordpress-test-data-with-lots-of-photos-ja.xml
  when: not wordpres_test_data_xml_st.stat.exists
  tags: ["wordpress_test_data"]
