---
timezone: Asia/Tokyo
ntp_servers:
  - ntp.jst.mfeed.ad.jp
  - ntp.nict.jp

mysql_root_password: "{{ lookup('env', 'MYSQL_ROOT_PASSWORD') }}"

apache_port: 8081

trafficserver_port: 80
trafficserver_retain_host_header: 1
trafficserver_remap_configs:
  - map http://192.168.33.131/ http://localhost:{{ apache_port }}/
  - reverse_map http://localhost:{{ apache_port }}/ http://192.168.33.131/

trafficserver_cache_configs:
  - dest_domain=localhost suffix=jpg ttl-in-cache=1m
  - dest_domain=localhost revalidate=1m

# https://docs.trafficserver.apache.org/en/latest/admin-guide/files/storage.config.en.html
# NOTE: Storage size must be at least 128MB
trafficserver_storage_configs:
  - /var/cache/trafficserver 128M

trafficserver_stats_over_http_pathinfo: "{{ lookup('env', 'STATS_OVER_HTTP_PATHINFO') }}"

wordpress_db_name: wordpress
wordpress_db_user: wordpress
wordpress_db_password: "{{ lookup('env', 'WORDPRESS_DB_PASSWORD') }}"
wordpress_install_dir: /var/www/html
wordpress_admin_name: admin
wordpress_admin_email: admin@example.com
wordpress_admin_password:  "{{ lookup('env', 'WORDPRESS_ADMIN_PASSWORD') }}"
wordpress_site_title: "Wordpress test site"
wordpress_site_url: "http://192.168.33.131"
