---
- name: Install php70 packages
  yum: name={{ item }} state=latest
  with_items:
    - php70-php
    - php70-php-cli
    - php70-php-gd
    - php70-php-mbstring
    - php70-php-mysqlnd
    - php70-php-xml
  notify: restart apache
  tags: ["php70"]

- name: Write /etc/opt/remi/php70/php.ini
  template: src=php.ini.j2 dest=/etc/opt/remi/php70/php.ini
  tags: ["php70"]
